---
- name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- debug:
    msg: "Current collectd plugins: {{ collectd_plugins }}"

- name: Get collectd-conf ConfigMap environment
  set_fact:
    collectd_conf_resource_configmap:
      env: "{{ lookup('template', 'configmap-collectd-conf.j2') }}"

- name: Setup collectd
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.to_load | default(True)
  loop:
    - name: serviceaccount.j2
    - name: clusterroles.j2
    - name: configmap-collectd-json.j2
    - name: configmap-collectd-conf.j2
    - name: daemonset-collectd.j2

- name: Setup Service for write_prometheus
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: 'collectd'
        namespace: '{{ meta.namespace }}'
        labels:
          component: collectd
      spec:
        ports:
        - name: collectd-write-prometheus
          port: "{{ collectd_plugin_write_prometheus_port }}"
          targetPort: "{{ collectd_plugin_write_prometheus_port }}"
          protocol: TCP
        selector:
          component: collectd
  when: '"write_prometheus" in collectd_plugins'
