---
- name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- debug:
    msg: "Current collectd plugins: {{ collectd_plugins }}"

- debug:
    msg: "{{ lookup('vars', item) }}"
  loop: "{{ collectd_plugins }}"

- debug:
    var: "{{ lookup('template', 'configmap-collectd-conf.j2') | from_yaml }}"


- name: Setup collectd
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.to_load | default(True)
  loop:
    - name: serviceaccount.j2
    - name: clusterroles.j2
    - name: configmap-collectd-json.j2
    - name: configmap-collectd-conf.j2
    - name: daemonset-collectd.j2
